CREATE TABLE IF NOT EXISTS Player_Attributes (
	id	INTEGER PRIMARY KEY AUTO_INCREMENT,
	player_fifa_api_id	INTEGER,
	player_api_id	INTEGER,
	date	VARCHAR(255),
	overall_rating	INTEGER,
	potential	INTEGER,
	preferred_foot	VARCHAR(255),
	attacking_work_rate	VARCHAR(255),
	defensive_work_rate	VARCHAR(255),
	crossing	INTEGER,
	finishing	INTEGER,
	heading_accuracy	INTEGER,
	short_passing	INTEGER,
	volleys	INTEGER,
	dribbling	INTEGER,
	curve	INTEGER,
	free_kick_accuracy	INTEGER,
	long_passing	INTEGER,
	ball_control	INTEGER,
	acceleration	INTEGER,
	sprint_speed	INTEGER,
	agility	INTEGER,
	reactions	INTEGER,
	balance	INTEGER,
	shot_power	INTEGER,
	jumping	INTEGER,
	stamina	INTEGER,
	strength	INTEGER,
	long_shots	INTEGER,
	aggression	INTEGER,
	interceptions	INTEGER,
	positioning	INTEGER,
	vision	INTEGER,
	penalties	INTEGER,
	marking	INTEGER,
	standing_tackle	INTEGER,
	sliding_tackle	INTEGER,
	gk_diving	INTEGER,
	gk_handling	INTEGER,
	gk_kicking	INTEGER,
	gk_positioning	INTEGER,
	gk_reflexes	INTEGER,
	FOREIGN KEY(player_fifa_api_id) REFERENCES Player(player_fifa_api_id),
	FOREIGN KEY(player_api_id) REFERENCES Player(player_api_id)
)