SELECT 
p.id, 
p.player_name, 
p.birthday, 
p.height, 
p.weight,
a.overall_rating,
a.potential,
a.preferred_foot,
a.attacking_work_rate,
a.defensive_work_rate,
a.crossing,
a.finishing,
a.heading_accuracy,
a.short_passing,
a.volleys,
a.dribbling,
a.curve,
a.free_kick_accuracy, 
a.long_passing,
a.ball_control,
a.acceleration,
a.sprint_speed,
a.agility,
a.reactions,
a.balance,
a.shot_power,
a.jumping,
a.stamina,
a.strength,
a.long_shots,
a.aggression,
a.interceptions,
a.positioning,
a.vision,
a.penalties,
a.marking,
a.standing_tackle,
a.sliding_tackle,
a.gk_diving,
a.gk_handling,
a.gk_kicking,
a.gk_positioning,
a.gk_reflexes
FROM Player p, Player_Attributes a
WHERE p.player_api_id = a.player_api_id AND p.player_fifa_api_id = a.player_fifa_api_id
GROUP BY p.id
LIMIT 100
